### ISSUE TITLE
atomic-primops fails to compile under GHCJS 8.2.  It did  in previous versions

### ISSUE THREAD

**Issue by agocorona** [ghcjs/ghcjs#707] opened 2018-10-25 09:22 UTC
```
[14 of 15] Compiling Data.Primitive.UnliftedArray ( Data/Primitive/UnliftedArray.hs, dist/build/Data/Primitive/UnliftedArray.js_o )
panic! (the 'impossible' happened)
  (GHCJS version 8.2.0.1, GHC version 8.2.2):
        assignAllCh: lengths do not match: (1,2)
    genApp

Please report this as a GHCJS bug:  https://github.com/ghcjs/ghcjs/issues

cabal: Leaving directory '/tmp/cabal-tmp-3647/primitive-0.6.4.0'
cabal: Error: some packages failed to install:
atomic-primops-0.8.2-4eNoLD4bOb6KWhtNtSKcAQ depends on atomic-primops-0.8.2
which failed to install.
primitive-0.6.4.0-GBGDBtp5CPg57QbAEq309u failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by hvr** [comment] 2018-10-25 10:54
Duplicate of #665

Workaround: avoid `primitive-0.6.4.0` via e.g.  `--constraint 'primitive < 0.6.4'`

**Comment by luite** [comment] 2018-10-30 15:45
should work with the latest commits on 8.4

**Closed as completed** 2018-12-25 14:27 UTC
