### ISSUE TITLE
Firefox is warning about mutating an object prototype

### ISSUE THREAD

**Issue by teh** [ghcjs/ghcjs#315] opened 2015-03-27 11:56 UTC
While running the simple hello world 
```
main = putStrLn "Hello, world!"
```

I see on my dev console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create - rts.js:2274:8
```

I'm sure you already know this, just wanted to make a note :)

**Comment by luite** [comment] 2015-03-31 02:00
I think this is caused by one of the dependencies of the RTS, and I think it's actually not modifying the prototype if the required functionality is already supported. I'll check if there are updates available.

**Comment by teh** [comment] 2015-03-31 10:35
Apologies, forgot to mention version: 36.0.4 - thanks for checking.

**Comment by luite** [comment] 2015-06-19 11:27
closing since this this happens in a third party lib, it probably only affects IE8 and IE9, all other browsers should use native typed arrays.

**Closed by luite** 2015-06-19 11:27 UTC
