### ISSUE TITLE
Error while building `gl`

### ISSUE THREAD

**Issue by schell** [ghcjs/ghcjs#498] opened 2016-07-05 18:19 UTC
I'm trying to build a program that depends on the [gl](https://github.com/ekmett/gl) package and ran into this error:

    [1 of 6] Compiling Utils            ( Utils.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Utils.js_o )
    [2 of 6] Compiling Module           ( Module.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Module.js_o )
    [3 of 6] Compiling Registry         ( Registry.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Registry.js_o )
    [4 of 6] Compiling Parser           ( Parser.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Parser.js_o )
    [5 of 6] Compiling Generator        ( Generator.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Generator.js_o )
    [6 of 6] Compiling Main             ( /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/Setup.hs, /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/Main.js_o )
    Linking /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/setup.jsexe (Generator,Main,Module,Parser,Registry,Utils)
    
    /private/var/folders/t8/nnlph4js2sx79l45ty30rqdc0000gn/T/stack50028/gl-0.7.8.1/.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/setup/setup:6136
            throw ("h$setField: setter not implemented for field: " + n);
            ^
    h$setField: setter not implemented for field: 101

Any thoughts?

**Comment by luite** [comment] 2016-07-06 09:39
This is caused by the packed metadata initializer only supporting objects up to 100 fields. the best solution is probably to generate this part of the code dynamically at link time.

I'll be working on making naming a bit more flexible soon, and might need to make this change anyway. Will take this issue into account.

In the meantime, can you check if you can work around this problem by adding `-debug` to the ghcjs command line when linking?

**Comment by luite** [comment] 2016-07-18 10:42
pull request merged, since only a few new setters were needed. thanks for the fix.

more flexible naming still coming

**Closed by luite** 2016-07-18 10:42 UTC
