### ISSUE TITLE
Another problem with weak references and reactive-banana (different behavior in GHC vs GHCJS)

### ISSUE THREAD

**Issue by ocharles** [ghcjs/ghcjs#463] opened 2016-02-11 09:22 UTC
cc @HeinrichApfelmus

The following program exhibits different behavior under GHC and GHCJS:

``` haskell
module Main (main) where

import Control.Concurrent
import Control.Monad
import Reactive.Banana
import Reactive.Banana.Frameworks

text_ :: Behavior String -> MomentIO (Behavior [()])
text_ contents =
  do contentsChanged <- changes contents
     reactimate' (fmap (fmap (const (print "X"))) contentsChanged)
     return (pure [()])

joinB :: Behavior (MomentIO (Behavior [()]))
      -> MomentIO (Behavior [()])
joinB b =
  do changed <- changes b
     initialB <- join (valueB b)
     laterB <- execute (b <@ changed)
     switchB initialB laterB

main :: IO ()
main =
  do n <-
       compile (do (tick,fireClick) <- newEvent
                   liftIOLater $
                     void $
                     forkIO $ forever $ threadDelay 1000000 >>= fireClick
                   reactimate (fmap print tick)
                   list <- accumB [] (fmap (:) tick)
                   nodes <-
                     joinB (fmap (fmap (fmap concat . sequenceA) .
                                  mapM (text_ . pure . show))
                                 list)
                   nodesChanged <- changes nodes
                   reactimate' (fmap (fmap (const (putStrLn "Changed"))) nodesChanged))
     actuate n
     forever (threadDelay maxBound)
```

In `ghc`:

```
()
Changed
()
Changed
()
Changed
()
Changed
()
Changed
()
Changed
()
Changed
```

In `ghcjs`:

```
()
Changed
()
Changed
()
Changed
<no more output>
```

In GHCJS it runs printing for 3 events and then stopping - suggesting a garbage collection has occured. In GHCI (and GHC compiled binaries) it counts without interruption (I aborted at 100, which takes 100 seconds).

I am running:
- `ghcjs-boot 97dea5c4145bf80a1e7cffeb1ecd4d0ecacd5a2f`
- `ghcjs-shims 45f44f5f027ec03264b61b8049951e765cc0b23a`
- `ghcjs 561365ba1667053b5dc5846e2a8edb33eaa3f6dd`

@HeinrichApfelmus, I have also tried with the `ghcjs` branch of `reactive-banana` and the same problem occurs with that. I can also note that if I change the definition of `text_` to just

``` haskell
text_ :: Behavior String -> MomentIO (Behavior [()])
text_ contents = return (pure [()])
```

the two programs behave identically. So it seems that by adding that extra `reactimate'`, the dependency graph is different enough to exhibit different GC patterns. It is very strange to me that `()` doesn't even get printed, so we seem to be losing almost the entire graph. The click thread is still alive, if we add a `print` statement for every iteration of the `forever` loop, you'll see that, but nothing will actually happen otherwise.

**Comment by luite** [comment] 2016-02-11 23:37
hmm, may be related to issue #454.

**Comment by HeinrichApfelmus** [comment] 2016-02-12 11:44
I didn't have time to look at this in detail yet, so just a quick remark: Did you check that the compiled GHC/GHCi version performs at least one garbage collection, so that the versions are doing something comparable? You can use `System.Mem.performGC` to trigger a GC.

**Comment by ocharles** [comment] 2016-02-14 09:47
I added an explicit call to `performGC` and the results are very strange.

GHC:

```
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
()
Changed
Performing a GC
Waiting
```

GHCJS:

```
Performing a GC
lib.js:1710 Waiting
lib.js:1710 ()
lib.js:1710 Changed
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 ()
lib.js:1710 Changed
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 ()
lib.js:1710 Changed
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 ()
lib.js:1710 Changed
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 ()
lib.js:1710 Changed
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 Performing a GC
lib.js:1710 Waiting
lib.js:1710 Performing a GC
lib.js:1710 Waiting
```

Note that it stops working, but seems independent of the amount of times I invoke `performGC`. Is `performGC` thread specific?

**Comment by achirkin** [comment] 2016-07-21 13:51
I think I have the same problem.
I tried another simple code snippet:
```haskell
module Main where

import Control.Monad (forM, forM_, forever)
import Data.IORef (newIORef, modifyIORef, readIORef)
import Reactive.Banana.Frameworks

hNUM :: Int
hNUM = 5

main :: IO ()
main = do
    (reg, run) <- genEvents
    handlers <- makeHandlers hNUM reg
    network <- compile . forM_ handlers $ \ah -> do
          ev <- fromAddHandler ah
          reactimate $ print <$> ev
    actuate network
    forever run

genEvents :: IO (Handler Int -> IO (), IO ())
genEvents = do
  handlers <- newIORef []
  return (\h -> modifyIORef handlers (h:)
         , getLine >>= \l -> let x = length l
                             in readIORef handlers >>= mapM_ (\h -> h x)
         )

makeHandlers :: Int -> (Handler Int -> IO ()) -> IO [AddHandler Int]
makeHandlers n reg = forM [1..n] $ \i -> do
    (ah, fire) <- newAddHandler
    reg $ fire . (+i)
    return ah
```
To run this I used `cabal exec -- ghcjs --make test.hs && nodejs test.jsexe/all.js`
and `cabal exec -- ghc --make test.hs && ./test`
within a sandbox.

So this code registers a number of events to `readLine` action, then prints length of a line read plus id of a handler. With number of handlers `hNUM` from 0 to 4 both ghc and ghcjs behave identically;
with `hNUM` >= 5 events fire only for the first fractions of a second after the first `readLine` (i.e. if you type fast enough, you may be able to trigger expected events 2-3 times ).

Originally, I wanted to post this comment into [ghcjs/pull/25](https://github.com/ghcjs/shims/pull/25) discussion.
Also I think that following bug reports may be related:
[reactive-banana/issues/109](https://github.com/HeinrichApfelmus/reactive-banana/issues/109), [ghcjs/issues/109](https://github.com/ghcjs/ghcjs/issues/450), or maybe even [ghcjs-shims/issues/109](https://github.com/ghcjs/shims/issues/3)?

**Comment by luite** [comment] 2016-07-21 19:17
Ok, I'll look into this again, last time I had some trouble reproducing the problem with the latest commits. I hope it's better now.

**Comment by achirkin** [comment] 2016-07-27 15:26
Thanks!
Any advances? Can you reproduce the problem? May I help anyhow?
I am sorry for my impatience, but this is a really problematic roadblock for my project!

**Comment by achirkin** [comment] 2016-08-06 12:26
After some number of experiments I managed to drastically simplify the example. No dependencies at all! To be honest, I am not sure if this is exactly the same problem as in the previous example, but behaviour of `ghc` and `ghcjs` differs clearly in this example (tested with `ghc-7.10.3`).

```haskell
module Main where

import Control.Concurrent (threadDelay)
import System.Mem (performGC)
import System.Mem.Weak (deRefWeak, mkWeak)


data Key = Key (IO Key) | RealKey
instance Show Key where
  show (Key _) = "Key ref"
  show (RealKey) = "RealKey"

main :: IO ()
main = do
    let key = RealKey
        key' = Key $ return key
    handler <- mkWeak key (print key) Nothing
    let loop = do
          threadDelay 100000
          mcall <- deRefWeak handler
          performGC
          case mcall of
            Nothing -> putStrLn "Dead."
            Just c  -> putStr "Got: " >> c >> loop
    loop
    print key'
```
Being compiled with `ghcjs` this program finishes with `"Dead"` after the first garbage collection (`"Got: RealKey"` printed once).

Being compiled with `ghc` this program loops indefinitely with `"Got: RealKey"`.

Seems like `ghcjs` does not count references within `IO` actions.

**Comment by achirkin** [comment] 2016-08-09 06:55
I am sorry for flooding, but this time I think I have found the problem. Though my [previous comment](https://github.com/ghcjs/ghcjs/issues/463#issuecomment-238021020) shows code with really different behaviour in `ghc` and `ghcjs`, I believe it is not related to original problem.

This time I think  the problem is in `vault` package; particularly, in `-useghc` default option. This option enables `unsafeCoerce` + `Any` data type approach instead of using `IORef`s. I think this causes JS engine to loose references to weak pointer objects, but I am not sure how `Any` and `unsafeCoerce` work in `ghcjs`. Turning this flag off makes the code in [my first comment](https://github.com/ghcjs/ghcjs/issues/463#issuecomment-234259225) behave in `ghcjs` exactly the same as in `ghc`.

So, apparently, compiling `vault` with `-f -useghc` seems to workaround the problem in `reactive-banana` (please, someone test it, maybe it just postpones the bug occurrence?..). Then my question is: what should we do next?

**Comment by achirkin** [comment] 2016-08-09 15:28
I am sorry for flooding, but this time I think I have found the problem. Though my [previous comment](https://github.com/ghcjs/ghcjs/issues/463#issuecomment-238021020) shows code with really different behaviour in `ghc` and `ghcjs`, I believe it is not related to the original problem.

This time I think  the problem is in `unordered-containers` package; particularly, `Data.HashMap.Strict` behaves buggy. This causes elements stored in `Reactive.Banana.Prim.OrderedBag`  be not tracked by GC. The only glue I found when I was looking through javascript output objects of haskell program is that one of the produced cryptic objects is an array :). This array does not have `__ghcjsArray` property when `hNUM = 5` and does have it  `__ghcjsArray = true` when `hNUM = 4`.
I did a workaround by changing `Data.HashMap.Strict`  with `Data.Map.Strict` and this seem to solve the problem! The change is available at [my fork](https://github.com/achirkin/reactive-banana-ghcjs-workaround/commit/5b5d0f784441ff81b8377c9b7825107013bf90c1) of reactive-banana.
Applying this change  makes the code in [my first comment](https://github.com/ghcjs/ghcjs/issues/463#issuecomment-234259225) behave in `ghcjs` exactly the same as in `ghc`.

Now I am really running out of time and continue with what I have at the moment. If anybody have time for this, I think it makes sense to test `unordered-containers` implementation together with weak pointers.

**Comment by bitonic** [comment] 2017-12-20 15:20
I'm witnessing similar buggy behavior with `Data.HashMap.Strict` and weak references and I've reached the same conclusion as @achirkin . Did anybody end up doing some more research on this?

**Comment by achirkin** [comment] 2017-12-20 15:34
Unfortunately, I was not able to replicate the bug using `Data.HashMap.Strict` alone at that time (experienced it via `reactive-banana` only).  @bitonic , did you manage to replicate it with `unordered-containers` alone?

**Comment by bitonic** [comment] 2017-12-20 15:36
@achirkin i did not, it's in a relatively large application. however, given this clue:

> This array does not have __ghcjsArray property when hNUM = 5 and does have it __ghcjsArray = true when hNUM = 4.

i went looking and these primops are definitely fishy: https://github.com/ghcjs/ghcjs/blob/3959a9321a2d3e2ad4b8d4c9cc436fcfece99237/src/Gen2/Prim.hs#L655 . the `.slice()` will not preserve the `__ghcjsArray` property:
```
genPrim _ _ CloneSmallArrayOp          [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); |]
genPrim _ _ CloneSmallMutableArrayOp   [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); |]
genPrim _ _ FreezeSmallArrayOp         [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); |]
genPrim _ _ ThawSmallArrayOp           [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); |]
```
unless i'm mislead, they should be something like
```
genPrim _ _ CloneSmallArrayOp          [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); `r`.__ghcjsArray = true; |]
genPrim _ _ CloneSmallMutableArrayOp   [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); `r`.__ghcjsArray = true; |]
genPrim _ _ FreezeSmallArrayOp         [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); `r`.__ghcjsArray = true; |]
genPrim _ _ ThawSmallArrayOp           [r]   [a,o,n]       = PrimInline [j| `r` = `a`.slice(`o`,`o`+`n`); `r`.__ghcjsArray = true; |]
```

i'll see if that fixes it.

**Comment by bitonic** [comment] 2017-12-20 15:50
here is the change i'm testing: https://github.com/bitonic/ghcjs/commit/7805639c0074f38e18c9f7a0b2c7e32dd7a4c6be CC @luite

**Comment by bitonic** [comment] 2017-12-20 16:12
similar fix for the normal arrays: https://github.com/bitonic/shims/commit/6d55e334473f5aac2d2269403eb43fb671214611

**Comment by bitonic** [comment] 2017-12-20 16:24
@achirkin actually, i've checked and in my application it's never the case that the GC stumbles on an array without `__ghcjsArray`. i think the two changes above are necessary anyway, but i don't think they're related to my problem regarding HashMap + weak references.

**Comment by bitonic** [comment] 2017-12-20 17:34
as predicted the two fixes above do not fix my problem :(.

nonetheless, i've opened two prs: https://github.com/ghcjs/ghcjs/pull/619 and https://github.com/ghcjs/shims/pull/45 .

**Comment by achirkin** [comment] 2017-12-21 08:37
Hmm, besides `__ghcjsArray` there is another additional [field `m` that is initialized with zero](https://github.com/ghcjs/shims/blob/c275ffca803150efb90a4f97402a9c865e73929a/src/mem.js#L937).
As I understand from [garbage collector shims](https://github.com/ghcjs/shims/blob/c275ffca803150efb90a4f97402a9c865e73929a/src/gc.js), it is used to mark objects by GC to decide if an object has to be deleted.
Maybe we also need to re-initialize or copy this field on slice?

**Comment by bitonic** [comment] 2017-12-21 08:40
@achirkin yes the `m` field is for the garbage collector (it starts at 0 and then alternates between 3 and 2). you're right, we should probably set that too. again, i doubt this is relevant to at least my problem though since the slicing functions are never used and the bug still manifests itself.

i also think that not setting the `m` field would actually "accidentally" work anyway, since most of the tests on that field are like `c.m !== 3` or `c.m !== 2`, which would work fine if the field is not set.

**Comment by bitonic** [comment] 2017-12-21 23:43
@achirkin actually it turns out that that `m` property _did_ matter! adding that fix too fixes this problem. sadly i do not have a self contained tests but i have thoroughly tested it in my application.

**Comment by bitonic** [comment] 2017-12-21 23:53
@luite once you merge the two prs above this can be closed, however it would be good to have a chat to find out exactly why that was causing trouble.

**Comment by bitonic** [comment] 2017-12-21 23:58
@ocharles btw, do you recall which "other" issues there were with weak references? i rely on them quite critically (as do other users, e.g. reflex), and it'd be good to make sure that at least all the known issues are fixed.

**Comment by ocharles** [comment] 2017-12-22 00:03
Sorry @bitonic, it's been a loooong time since I looked. But it might be worth re-running my above tests.

**Comment by jaspervdj** [comment] 2018-02-04 11:28
I also ran into (a variation of) this problem.  @bitonic 's PRs fix the issue for me.  Would be good to get those merged.

**Comment by luite** [comment] 2018-02-04 18:17
ah thanks for bringing it to my attention again. I'll apply the fix.

**Closed** 2018-03-20 17:08 UTC
