### ISSUE TITLE
ghcjs + node - readProcess (or any runInteractiveProcess) fails to read from stdout

### ISSUE THREAD

**Issue by kmandelbaum** [ghcjs/ghcjs#453] opened 2016-01-05 22:25 UTC
Hello!

I'm having an issue with ghcjs and interactive process routines family.

Setup:
```
Linux kenny 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0 (GHC 7.10.3)
The Glorious Glasgow Haskell Compilation System, version 7.10.3
node v5.3.0
```

`Main.hs` contents:
```
import System.Process
import System.IO
main = do
  x <- readProcess "echo" ["123"] []
  print x
```

Reproduction:
```
ghcjs Main.hs
node Main.jsexe/all.js
```

Output:
```
""
```

 * This example works with ghc - native binary output is "123".
 * If I use "touch" instead of "echo", the file "123" is created, so the process launching seems to work.
 * It looks like is's some piping that is broken/not implemented(?), because hGetContents seems to be working fine on non-pipe files (should check with the standalone pipes, though, without creating processes...)
 * I've found out this in attempts to investigate the failure of `ghcjs-boot`, when building cabal, when the `Setup.hs` got build by ghcjs, producing a javascript version of the setup, which was not able to determine ghcjs's version, like this, so my `ghcjs-boot` failed:
```
setup: The program 'ghcjs' version >=0.1 is required but the version of
/home/kost/.cabal/bin/ghcjs could not be determined.
```

Can anyone else reproduce?

**Comment by kmandelbaum** [comment] 2016-01-05 23:42
My initial problem looked just like #436 `alios`'s problem.

**Comment by luite** [comment] 2016-01-11 23:31
Looks like node.js 5.3.0 is problematic, 5.0.0 works. I'll look into this. Have you found any more information?

**Comment by kmandelbaum** [comment] 2016-01-27 22:23
Thank you! Works for me with node.js 5.0.0

**Comment by awpr** [comment] 2016-01-28 07:50
I suspect some change related to the streams3 API in Node broke child process streams.  Some very aggressive inlining and shrinking of the Haskell repro program above gives the following JS program, which behaves differently on node 0.10.36.3 and 5.5.0.1 (oddly most of the intervening versions are missing library dependencies on my system, so I don't have tighter version bounds):

const spawn = require('child_process').spawn;
const ls = spawn('echo', ['123']);

console.log("flowing:", ls.stdout._readableState.flowing);
ls.stdout.on('readable', function() {
    console.log("read:", ls.stdout.read());
});

On 0.10, it reports "flowing: false" and sees the full contents of the stream; while on 5.5, it reports "flowing: null" and sees only the end-of-stream (but none of the contents).  It looks to me like the stream is created unpaused, and the data is lost into the void.

If I recall correctly, some people reporting bugs caused by this ("version of ghcjs could not be determined" or similar) have mentioned that it was flaky, and could sometimes be worked around by re-running the build, which is consistent with a race between event handler registration and data availability.  In fact, I've just made nodejs-5.5 successfully read some data by changing the process to "cat /tmp/some_named_fifo" and writing to the FIFO after a delay (to force the race to go the other way).

**Comment by mgsloan** [comment] 2016-01-28 08:49
Wow, awesome diagnosis @awpr!

There's something somewhat comical about issues during GHCJS build processes causing us to find previously unknown node bugs (guessing they're unknown, because [this search](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+flowing+spawn) doesn't turn up anything)

**Comment by luite** [comment] 2016-02-06 23:04
I do get the same result for v4.x and v5.5.x here though, with this test. Is this really the root cause of the problem (and does some unrelated issue make it easier to trigger on 5.5?), or is there something else?

**Comment by luite** [comment] 2016-02-09 22:57
Ok, still no merge, but I built node.js from source and it looks like the patch indeed fixes the whole problem as far as I can reproduce it. Thanks for investigating @awpr !

Unfortunately the child_process `spawn` method is rather picky in what it accepts as streams: It either creates a new stream, sends things to an existing file descriptor or needs something with superclass `Pipe`. I haven't found a good way to work around the problem for this reason. It seems that blacklisting v5.x up to the first version with the fix (hopefully v5.5.1) is the next best thing (same for v4.x, although we may be a bit more lenient here, since somehow the problem is harder to trigger there)

does anyone have suggestions on how to make it easiest for users to deal with this problem?

**Comment by mgsloan** [comment] 2016-02-10 00:21
I think these two things ought to be done:

* Have booting check for these broken node versions

* Also have stack check node version, so that users will get notified about this when using ghcjs versions before the check is added.

There's also the case that ghcjs has managed to successfully boot.  There are a couple ways to address this:

1) Have `ghcjs` check node version on startup.  I don't like this because not all uses of `ghcjs` necessarily require node.

2) Have the particular affected invocations of `spawn` check node version and fail.

Ideally we'd have a workaround in the use of spawn, conditional on node version.  Is this not possible?

**Comment by luite** [comment] 2016-02-10 03:18
I haven't found a good workaround yet. For those interested in investigating, this is what I looked into:

`spawn` calls `_validateStdio` implemented in `node/lib/internal/child_process.js`. Perhaps we can attach some wrapping stream (see the `getHandleWrapType` call) and make sure that event handlers have been attached before the `spawn` call?

I don't know how to proceed from here though.

**Comment by luite** [comment] 2016-02-10 04:06
I have a workaround now, fix coming up

**Comment by luite** [comment] 2016-02-10 05:43
That should do it: ghcjs/shims@4df1808d03117ddcd45f276f0ddd85c73e59506a . Please let me know if it works.

Once the fix is in a released version of node.js, a version check should probably be added, or at least a comment.

**Comment by 3noch** [comment] 2016-02-10 13:58
Awesome!

**Comment by mgsloan** [comment] 2016-02-27 00:58
So, what guidance on this should be given in http://docs.haskellstack.org/en/stable/ghcjs/ ?  I can think of two options:

* Recommend always using node 0.*.

* Recommend using node 0.*, but only for ghcjs versions before this fix.

Similarly, I would like to have stack automatically install node - https://github.com/commercialhaskell/stack/issues/1632 .  If the 2nd bullet is the approach we want to take, then perhaps we can get a version bump in ghcjs, so that stack can detect when it supports recent node.

Does ghcjs want to do anything about specifying a recommended node version that can be used by tools like stack, or should this be something maintained by stack?

**Comment by luite** [comment] 2016-02-27 01:06
ghcjs-boot does check the version, but at the moment it's only a minimum bound.

**Comment by mgsloan** [comment] 2016-02-27 01:42
Right, but what version of node should we tell users to use / automatically install?

**Comment by tolysz** [comment] 2016-09-05 21:48
It looks like fixed issue (when used with `stack`):

latest node

    > node --version
    v6.5.0

with lts-6.15/master

    > stack ghc -- --version
    The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0.9006015 (GHC 7.10.3)

    > node all.js 
    "123\n"

with nightly-2016-09-04/ghc-8.0-20160905

    $ stack ghc -- --version
    The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0.820160904 (GHC 8.0.1)

    $ node all.js 
    "123\n"

Can we start closing old issues/ start compiling solutions so the next user will have an easy time using `ghcjs`?

**Comment by luite** [comment] 2016-09-05 22:18
ok, I think this is fixed then. The latest LTS and Current node should work everywhere at the moment. 

I think that we should try to make sure that the latest LTS always works (At least on current GHCJS)

**Closed by luite** 2016-09-05 22:18 UTC

**Comment by tolysz** [comment] 2016-09-05 22:28
If we choose platforms (eg something buildable via docker), choose tests we can create CI to test against various node versions.
