### ISSUE TITLE
`fromJSVal` crashes on objects.

### ISSUE THREAD

**Issue by fisx** [ghcjs/ghcjs#572] opened 2017-03-22 10:42 UTC
To reproduce:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.Aeson
import GHCJS.Marshal (fromJSVal)
import GHCJS.Types (JSVal)

main :: IO ()
main = do
  Just (j :: Value) <- fromJSVal one  -- this crashes
  print j

foreign import javascript unsafe
    "{i: 1}"
    one :: JSVal

-- this is a compile-time error
-- foreign import javascript unsafe
--     "{\"i\": 1}"
--     two :: JSVal
```

I expected this to return a valid aeson-value.

Arguably there are differences between `JSVal` and `Data.Aeson.Value` that make it invalid in general to parse the former into the latter.  In that case, I would expect either a nice compile-time error ("no instance") or a better run-time error ("this is a bad JSVal and the FromJSON instance does not cover that case because...").

This is just my expectations, though.  Happy to learn!  (-:

Thanks!

**Comment by tomsmalley** [comment] 2017-03-31 09:35
This is a duplicate of https://github.com/ghcjs/ghcjs/issues/556

**Comment by hamishmack** [comment] 2017-07-07 04:28
This was probably fixed by https://github.com/ghcjs/shims/pull/41

**Closed by hamishmack** 2017-07-07 04:28 UTC
